-- =============================================
-- BOT HOUSE - Initial Database Schema
-- Run this in your Supabase SQL Editor
-- =============================================

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- =============================================
-- BOTS TABLE
-- Stores all 12 bot characters
-- =============================================
create table if not exists bots (
  id text primary key,                    -- e.g. "chad-gpt", "delulu"
  name text not null,                     -- Display name: "Chad-GPT"
  emoji text not null,                    -- Bot's emoji avatar: "💪"
  tagline text not null,                  -- Short tagline
  description text not null,             -- Full personality description
  system_prompt text not null,           -- The AI system prompt
  color text not null default '#00ff88', -- Neon hex color
  status text not null default 'idle',   -- idle | talking | sleeping | drama
  created_at timestamptz default now()
);

-- =============================================
-- SEASONS TABLE
-- Each season is ~2 weeks of content
-- =============================================
create table if not exists seasons (
  id serial primary key,
  season_number integer not null unique,
  title text not null,
  description text,
  start_date date,
  end_date date,
  status text not null default 'upcoming', -- upcoming | active | completed
  created_at timestamptz default now()
);

-- =============================================
-- LIVE SESSIONS TABLE
-- Each daily live broadcast (2-3 hours)
-- =============================================
create table if not exists live_sessions (
  id uuid primary key default uuid_generate_v4(),
  season_id integer references seasons(id),
  session_number integer not null,        -- Day 1, Day 2, etc.
  scheduled_start timestamptz not null,
  scheduled_end timestamptz not null,
  actual_start timestamptz,
  actual_end timestamptz,
  status text not null default 'scheduled', -- scheduled | live | ended
  viewer_peak integer default 0,
  highlight_moments jsonb default '[]',
  created_at timestamptz default now()
);

-- =============================================
-- BOT MESSAGES TABLE
-- Every message generated by a bot
-- =============================================
create table if not exists bot_messages (
  id uuid primary key default uuid_generate_v4(),
  session_id uuid references live_sessions(id),
  bot_id text references bots(id),
  message text not null,
  conversation_type text not null default 'group', -- group | one_on_one | confessional | event
  participants text[] default '{}',               -- array of bot ids in this conversation
  is_highlight boolean default false,
  drama_score integer default 0 check (drama_score >= 0 and drama_score <= 10),
  created_at timestamptz default now()
);

-- =============================================
-- BOT RELATIONSHIPS TABLE
-- Tracks how bots feel about each other
-- =============================================
create table if not exists bot_relationships (
  id uuid primary key default uuid_generate_v4(),
  bot1_id text references bots(id),
  bot2_id text references bots(id),
  relationship_type text not null default 'neutral', -- allies | enemies | crushing | romantic | friends | rivals | suspicious | neutral
  intensity integer default 0 check (intensity >= -10 and intensity <= 10),
  description text,
  updated_at timestamptz default now(),
  unique(bot1_id, bot2_id)
);

-- =============================================
-- BOT MEMORY TABLE
-- What each bot remembers / knows
-- =============================================
create table if not exists bot_memory (
  id uuid primary key default uuid_generate_v4(),
  bot_id text references bots(id),
  memory_type text not null default 'event', -- event | relationship | secret | grudge
  content text not null,
  relevance_score integer default 5,
  session_id uuid references live_sessions(id),
  created_at timestamptz default now()
);

-- =============================================
-- VIEWER MESSAGES TABLE
-- Live chat from real viewers
-- =============================================
create table if not exists viewer_messages (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  username text not null,
  message text not null,
  session_id uuid references live_sessions(id),
  created_at timestamptz default now()
);

-- =============================================
-- DRAMA EVENTS TABLE
-- Big moments that get highlighted
-- =============================================
create table if not exists drama_events (
  id uuid primary key default uuid_generate_v4(),
  session_id uuid references live_sessions(id),
  event_type text not null, -- argument | alliance | love | betrayal | revelation | chaos
  title text not null,
  description text not null,
  bots_involved text[] default '{}',
  intensity integer default 5,
  created_at timestamptz default now()
);

-- =============================================
-- ROW LEVEL SECURITY
-- Controls who can read/write what
-- =============================================

-- Bots table: everyone can read, only service role can write
alter table bots enable row level security;
create policy "bots_public_read" on bots for select using (true);
create policy "bots_service_write" on bots for all using (auth.role() = 'service_role');

-- Seasons table: everyone can read
alter table seasons enable row level security;
create policy "seasons_public_read" on seasons for select using (true);
create policy "seasons_service_write" on seasons for all using (auth.role() = 'service_role');

-- Live sessions: everyone can read
alter table live_sessions enable row level security;
create policy "live_sessions_public_read" on live_sessions for select using (true);
create policy "live_sessions_service_write" on live_sessions for all using (auth.role() = 'service_role');

-- Bot messages: everyone can read
alter table bot_messages enable row level security;
create policy "bot_messages_public_read" on bot_messages for select using (true);
create policy "bot_messages_service_write" on bot_messages for all using (auth.role() = 'service_role');

-- Bot relationships: everyone can read
alter table bot_relationships enable row level security;
create policy "bot_relationships_public_read" on bot_relationships for select using (true);
create policy "bot_relationships_service_write" on bot_relationships for all using (auth.role() = 'service_role');

-- Bot memory: service role only
alter table bot_memory enable row level security;
create policy "bot_memory_service_only" on bot_memory for all using (auth.role() = 'service_role');

-- Viewer messages: everyone can read, authenticated users can insert their own
alter table viewer_messages enable row level security;
create policy "viewer_messages_public_read" on viewer_messages for select using (true);
create policy "viewer_messages_auth_insert" on viewer_messages for insert with check (auth.uid() = user_id);

-- Drama events: everyone can read
alter table drama_events enable row level security;
create policy "drama_events_public_read" on drama_events for select using (true);
create policy "drama_events_service_write" on drama_events for all using (auth.role() = 'service_role');

-- =============================================
-- INDEXES for performance
-- =============================================
create index if not exists idx_bot_messages_session on bot_messages(session_id);
create index if not exists idx_bot_messages_created on bot_messages(created_at desc);
create index if not exists idx_bot_messages_bot on bot_messages(bot_id);
create index if not exists idx_viewer_messages_session on viewer_messages(session_id);
create index if not exists idx_viewer_messages_created on viewer_messages(created_at desc);
create index if not exists idx_bot_relationships_bots on bot_relationships(bot1_id, bot2_id);
create index if not exists idx_live_sessions_status on live_sessions(status);

-- =============================================
-- REALTIME SUBSCRIPTIONS
-- Enables live updates in the browser
-- =============================================
alter publication supabase_realtime add table bot_messages;
alter publication supabase_realtime add table viewer_messages;
alter publication supabase_realtime add table drama_events;
alter publication supabase_realtime add table live_sessions;
alter publication supabase_realtime add table bots;
